### PR TITLE
Add ability to get content's HTML

### PR DESCRIPTION
**Pull request by paskal**
In one of my projects, I used this one, and I had to fork it to have the ability to manipulate not only the resulting content but also its HTML representation. This PR proposes these changes to the upstream version of the library so I could switch back to it from the fork, and everyone could benefit from it.

### CODE REVIEW

**Comment by paskal** [comment]
@mauidude would you be so kind as to take a look into this one?

**Comment by paskal** [comment]
@mauidude could you please look into it?

**Comment by paskal** [comment]
@mauidude gentle ping.

**Review by mauidude — APPROVED** [review]

**Comment by paskal** [comment]
Thanks a lot!

**Pull request merged**
